### ISSUE TITLE
exception occurs when starting

### ISSUE THREAD

**Issue by blackcement** [AIDajiangtang/Segment-Anything-CSharp#10]
An exception occurs when starting the application

BadImageFormatException: An attempt was made to load a program that has an invalid format. (Exception from HRESULT: 0x8007000B)
![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/61663301/8beea39d-5d48-4fdb-9b24-2dcd5b0543e5)

![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/61663301/6de6ad49-a51c-43ce-8e7d-5bd2be4b73b1)

**Comment by AIDajiangtang** [comment]
https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=drive_link
i upload them to google drive,have a try

**Comment by blackcement** [comment]
> https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=drive_link i upload them to google drive,have a try

No access

**Comment by AIDajiangtang** [comment]
> https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=drive_link

sorry！try again

**Comment by AIDajiangtang** [comment]
> > https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=drive_link
> 
> sorry！try again

https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=sharing

**Comment by blackcement** [comment]
> > > https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=drive_link
> > 
> > 
> > sorry！try again
> 
> https://drive.google.com/drive/folders/1tP-Xvj8N3-iMmzbXN9OsPwliZRnC06If?usp=sharing

I replaced these files, nothing changed, still the same error 

Nuget packages as in the instructions

![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/61663301/0db43816-05c5-4991-9ff6-6f93266e1153)

**Comment by AIDajiangtang** [comment]
try to download them by yourself!

!wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/encoder-quant.onnx
!wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/decoder-quant.onnx
!wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/visual.onnx
!wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/textual.onnx

**Comment by blackcement** [comment]
> try to download them by yourself!
> 
> !wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/encoder-quant.onnx !wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/decoder-quant.onnx !wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/visual.onnx !wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/textual.onnx

Nothing has changed (((
w10x64 Ryzen 7 2700 8-core, 32GB RAM, RX-560

I understand correctly that the calculations will be done on the processor and NVIDIA and CUDA are not needed?

**Comment by AIDajiangtang** [comment]
not relay on cuda, onnxruntime is cpu version.
can you debug?any of there four models can not be loaded?
is it because of the none english environment?

**Comment by jacksinofn** [comment]
@blackcement 我也遇到同样的问题，请问您解决了么，需要怎么左。

**Comment by blackcement** [comment]
> @blackcement 我也遇到同样的问题，请问您解决了么，需要怎么左。

@jacksinofn, No I haven't decided


> not relay on cuda, onnxruntime is cpu version. can you debug?any of there four models can not be loaded? is it because of the none english environment?

@AIDajiangtang, I don't understand how you can debug the library. Neither textual.onnx nor visual.onnx are loaded. I don't think the language version of the environment is causing this issue.

"BadImageFormatException: An attempt was made to load a program that is in a bad format. (Exception from HRESULT: 0x8007000B)"

**Comment by AIDajiangtang** [comment]
@blackcement @jacksinofn 
try x64 not anyCPU
the target platform of onnxruntime is x64,so SAMViewer must be same with it

**Comment by blackcement** [comment]
> try to download them by yourself!
> 
> !wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/encoder-quant.onnx !wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/decoder-quant.onnx !wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/visual.onnx !wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/textual.onnx

Friend, as I understand it, this is the weakest model B? Where can I find the rest of B and H in onnx format?

**Comment by AIDajiangtang** [comment]
> !wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-B-32/textual.onnx

 this link contains segment-anything-vit-l
https://huggingface.co/visheratin/segment-anything-vit-l

this is for clip l
!wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-L-14/visual.onnx
!wget https://clip-as-service.s3.us-east-2.amazonaws.com/models/onnx/ViT-L-14/textual.onnx
