### ISSUE TITLE
无法使用vit_h' 和 'vit_l' 模型

### ISSUE THREAD

**Issue by kai3316** [AIDajiangtang/Segment-Anything-CSharp#13]
你好 感谢分享这个项目，使用自带的模型文件可以成果运行，但是复杂分割场景下的效果一般。在之前的issue中有说明可以使用以下huggingface上的权重，但我尝试后发现这里的模型无法使用， 使用'vit_b'模型也会出错，点击图片后会提示 image embedding is not done！请问需要对模型做什么处理吗？
!wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/encoder-quant.onnx
!wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/decoder-quant.onnx

**Comment by AIDajiangtang** [comment]
> 法使用， 使用'vit_b'模型也会出错

提示 image embedding is not done！就说明图像编码操作还没完成，编码是比较耗时的操作，换成'vit_b'后就会更耗时，同时内存和显存要求的也会更多，先确定下是没有完成还是因为资源限制抛出异常了

**Comment by kai3316** [comment]
谢谢回复，在出现image embedding cal finished 提示之后就可以正常使用了，之前选择完图片直接点击导致报错
