### ISSUE TITLE
Program crashes after opening image

### ISSUE THREAD

**Issue by BiologyTools** [AIDajiangtang/Segment-Anything-CSharp#2]
After loading an image the program crashes I expect it is because the model files are not correctly setup. How do I set the models correctly and fix the crashing issue? Best, Erik

**Comment by AIDajiangtang** [comment]
please make sure that the onnx pretrained model is in the same folder with SAMViewer.exe, I have uploaded the model,the download link is:https://github.com/AIDajiangtang/Segment-Anything-CSharp/tree/main/Model

**Comment by AIDajiangtang** [comment]
> After loading an image the program crashes I expect it is because the model files are not correctly setup. How do I set the models correctly and fix the crashing issue? Best, Erik
please make sure that the onnx pretrained model is in the same folder with SAMViewer.exe, I have uploaded the model,the download link is:https://github.com/AIDajiangtang/Segment-Anything-CSharp/tree/main/Model

**Comment by BiologyTools** [comment]
Even after placing the model files in the same directory as the executable the program still crashes after opening image.
![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/84872500/47c6e7c5-8d1b-457e-9eba-43d02aa3eae0)

**Comment by AIDajiangtang** [comment]
> Even after placing the model files in the same directory as the executable the program still crashes after opening image. ![image](https://user-images.githubusercontent.com/84872500/257046953-47c6e7c5-8d1b-457e-9eba-43d02aa3eae0.png)

you need unzip them first！
<img width="591" alt="11111" src="https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/18625471/e9afb3ab-6170-484c-ad36-5a8259013f0a">

**Comment by BiologyTools** [comment]
I've tried unzipping them but Winrar says that the archive is damaged.

**Comment by AIDajiangtang** [comment]
> I've tried unzipping them but Winrar says that the archive is damaged.

GitHub limits the size of uploaded files，you can try this:https://pan.baidu.com/s/1jiT7Ngn5XTiV51PQanrs1g?pwd=eim5
if not work,then try:
wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/encoder-quant.onnx
wget https://huggingface.co/visheratin/segment-anything-vit-b/resolve/main/decoder-quant.onnx

**Comment by BiologyTools** [comment]
Thank you! The program works now!

**Comment by AIDajiangtang** [comment]
> I've tried unzipping them but Winrar says that the archive is damaged.

something else need to take care:
1.you can use the promote after image embedding is done
<img width="738" alt="222" src="https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/18625471/f0df22c5-116b-4e4a-82bc-6f1951d23332">
2.everything and text promt has not done
