### ISSUE TITLE
使用新的MSBuild文件减少启动配置

### ISSUE THREAD

**Issue by feast107** [AIDajiangtang/Segment-Anything-CSharp#5]
当前项目使用的还是旧的 `.csproj` 文件，拉取之后需要手动安装依赖。我本地已经调整了项目结构，添加了 `.gitignore` ，如果需要的话我可以提一个 pull requrest 供您审核。

**Comment by feast107** [comment]
而且项目中还存在 `/bin` 输出目录，不是很符合规范

**Comment by AIDajiangtang** [comment]
> 当前项目使用的还是旧的 `.csproj` 文件，拉取之后需要手动安装依赖。我本地已经调整了项目结构，添加了 `.gitignore` ，如果需要的话我可以提一个 pull requrest 供您审核。

可以

**Comment by feast107** [comment]
Pull request 已经提交到 https://github.com/AIDajiangtang/Segment-Anything-CSharp/pull/6
