### ISSUE TITLE
Model Files only available on Baidu make them available in Releases.

### ISSUE THREAD

**Issue by BiologyTools** [AIDajiangtang/Segment-Anything-CSharp#7]
I'm trying to get all the model files (.onnx) but I am unable to download them from the Baidu link, as I can not register an account on Baidu without a Chinese phone number. You can add them to the release you have made by editing the release and adding the onnx files. There is no limit to the size of the files attached to releases as this is how I release my software which is over 400mb.

Here is a example image from how I share large files on GitHub in Releases:
![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/84872500/7600fad8-3955-4b5e-8c4f-d79b5cba59e9)

**Comment by AIDajiangtang** [comment]
> I'm trying to get all the model files (.onnx) but I am unable to download them from the Baidu link, as I can not register an account on Baidu without a Chinese phone number. You can add them to the release you have made by editing the release and adding the onnx files. There is no limit to the size of the files attached to releases as this is how I release my software which is over 400mb.
> 
> Here is a example image from how I share large files on GitHub in Releases: ![image](https://private-user-images.githubusercontent.com/84872500/296515941-7600fad8-3955-4b5e-8c4f-d79b5cba59e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjk4MzcsIm5iZiI6MTcwNTM2OTUzNywicGF0aCI6Ii84NDg3MjUwMC8yOTY1MTU5NDEtNzYwMGZhZDgtMzk1NS00YjVlLThjNGYtZDc5YjVjYmE1OWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAxNDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjODA1NGIzMTRjOTIyZmUxM2FiYWM1YTU2NWM2ZTYzYTQ3ZmM4NTA5MWZmMzg2MmU0YTEzZDg5ZDFlNzg4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LVnbKW7_ZU93MYeqOpFV0E8x3SPnh7_bjMYj_VUUuNM)

Sorry for the late reply. I have followed your method. I am very happy to have learned a new skill. Thank you.

**Comment by BiologyTools** [comment]
Thank you for all the model files.
