### ISSUE TITLE
请问如何将分割后的图像保存

### ISSUE THREAD

**Issue by zhangyuanwai** [AIDajiangtang/Segment-Anything-CSharp#8]
您好，

图像分割结果出来以后，直接保存mask源对应的bitmap会是一个半透明的灰图，请问如何保存分割区域对应的原图？请您不吝赐教，非常感谢！

示例区域：
![image](https://github.com/AIDajiangtang/Segment-Anything-CSharp/assets/31298446/ab70f7c3-fee2-402b-83e2-426bb4fd3f39)

**Comment by AIDajiangtang** [comment]
1.根据mask_threshold，将MaskData中的mMask生成一个二值图像Mat mask
2.加载原图像 OpenCvSharp.Mat image = OpenCvSharp.Cv2.ImRead(this.mImagePath, OpenCvSharp.ImreadModes.Color);
3.将二值图像mask与原图像image做位运算，生成结果图像Mat dest
4.调用OpenCV的图像保存方法

**Comment by zhangyuanwai** [comment]
收到，非常感谢。
