### ISSUE TITLE
decoder-quant.onnx , encoder-quant.onnx ,visual.onnx and textual.onnx

### ISSUE THREAD

**Issue by blackcement** [AIDajiangtang/Segment-Anything-CSharp#9]
Thanks for the work, but could you describe in detail where to get the files decoder-quant.onnx, encoder-quant.onnx, visual.onnx and textual.onnx? As I understand it, they are very large, could you post them on Google Drive?

**Comment by AIDajiangtang** [comment]
> Thanks for the work, but could you describe in detail where to get the files decoder-quant.onnx, encoder-quant.onnx, visual.onnx and textual.onnx? As I understand it, they are very large, could you post them on Google Drive?

I have upload to release
https://github.com/AIDajiangtang/Segment-Anything-CSharp/releases/download/v1.0.1/ONNXModels.zip
